export const ADVERTISERS_FETCH  = 'ADVERTISERS_FETCH';
export const ADVERTISERS_SEARCH = 'ADVERTISERS_SEARCH';

export const FAVORITE_TOGGLE  = 'FAVORITES_ADD';
export const FAVORITES_REMOVE = 'FAVORITES_REMOVE';
