export const ADVERTISERS_FETCH  = 'ADVERTISERS_FETCH';
export const ADVERTISERS_SEARCH = 'ADVERTISERS_SEARCH';

export const FAVORITES_ADD    = 'FAVORITES_ADD';
export const FAVORITES_REMOVE = 'FAVORITES_REMOVE';
